spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=${SECRET}
url=${URL}
jwt.expiration=3600
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.jackson.serialization.fail-on-empty-beans=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8


spring.mail.host=${MAIL_HOST}
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


