
spring.application.name=ponto_eletronico
spring.datasource.url=jdbc:mysql://localhost/db_ponto_eletronico?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
jwt.secret=your-secure-secret-key
jwt.expiration=3600 
spring.jpa.hibernate.ddl-auto=update

spring.jackson.serialization.fail-on-empty-beans=false

spring.messages.basename=messages
spring.messages.encoding=UTF-8


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kronos.time.tech.solutions@gmail.com
spring.mail.password=gvky thni xuoo wzon
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


